-- Spiro ERP — Phase 1 schema
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============ USERS & ACCESS ============
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT,
  password_hash TEXT,                        -- null until activation
  role TEXT NOT NULL DEFAULT 'operator'
    CHECK (role IN ('admin','manager','operator')),
  permissions JSONB NOT NULL DEFAULT '[]'::jsonb,  -- extra capabilities granted via activation code
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  activated_at TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Codes generated by the administrator; POS operators self-register with one
CREATE TABLE IF NOT EXISTS activation_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,
  label TEXT,                                -- e.g. "Kampala Road counter"
  role TEXT NOT NULL DEFAULT 'operator'
    CHECK (role IN ('manager','operator')),
  permissions JSONB NOT NULL DEFAULT '[]'::jsonb,  -- extra POS capabilities granted with this code
  created_by UUID REFERENCES users(id),
  claimed_by UUID REFERENCES users(id),
  used_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '7 days',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============ INVENTORY ============
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sku TEXT UNIQUE NOT NULL,
  barcode TEXT UNIQUE,
  name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Spare Parts'
    CHECK (category IN ('Spare Parts','Accessories','Consumables','e-Bikes','e-Bikes Spare Parts','e-Bike','e-Bike Spare Parts','Spare Parts','Spare part','Accessory','Consumable')),
  brand TEXT,
  supplier TEXT,
  cost_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  selling_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  stock_qty INTEGER NOT NULL DEFAULT 0,
  min_stock INTEGER NOT NULL DEFAULT 5,
  reorder_level INTEGER NOT NULL DEFAULT 10,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Individually traceable bikes (VIN-level inventory)
CREATE TABLE IF NOT EXISTS bikes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vin TEXT UNIQUE NOT NULL,
  model TEXT NOT NULL,                       -- e.g. Spiro Ekon
  color TEXT,
  year INTEGER,
  motor_number TEXT,
  battery_serial TEXT,
  battery_spec TEXT,
  odometer_km INTEGER NOT NULL DEFAULT 0,
  cost_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  selling_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'in_stock'
    CHECK (status IN ('in_stock','reserved','sold')),
  location TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sold_at TIMESTAMPTZ,
  sold_price NUMERIC(12,2),
  customer_id UUID,                          -- FK added after customers table
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Migration for older installs
ALTER TABLE bikes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE users ADD COLUMN IF NOT EXISTS permissions JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE activation_codes ADD COLUMN IF NOT EXISTS permissions JSONB NOT NULL DEFAULT '[]'::jsonb;

-- Role rename for POS access control: the two POS roles are `manager` and
-- `operator` (see server/src/permissions/catalog.js). `cashier` and `mechanic`
-- predate the permission catalog and are folded into `operator`. The CHECK
-- constraints are dropped BEFORE the UPDATEs and re-added afterwards: the old
-- definitions reject 'operator' mid-migration.
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE activation_codes DROP CONSTRAINT IF EXISTS activation_codes_role_check;
UPDATE users SET role = 'operator' WHERE role IN ('cashier', 'mechanic');
UPDATE activation_codes SET role = 'operator' WHERE role IN ('cashier', 'mechanic');
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('admin','manager','operator'));
ALTER TABLE activation_codes ADD CONSTRAINT activation_codes_role_check CHECK (role IN ('manager','operator'));

CREATE TABLE IF NOT EXISTS customers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  phone TEXT UNIQUE,
  email TEXT,
  address TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE bikes
  DROP CONSTRAINT IF EXISTS bikes_customer_id_fkey,
  ADD CONSTRAINT bikes_customer_id_fkey
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS customer_bikes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  bike_id UUID REFERENCES bikes(id) ON DELETE SET NULL,
  -- bikes owned that were not sold through this system
  external_desc TEXT,
  plate TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============ SALES ============
-- payment_method: cash | mobile_money | bank | card | credit
CREATE TABLE IF NOT EXISTS sales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_txn_id TEXT UNIQUE NOT NULL,        -- idempotency key from POS
  receipt_no TEXT UNIQUE,
  cashier_id UUID NOT NULL REFERENCES users(id),
  customer_id UUID REFERENCES customers(id),
  bike_id UUID REFERENCES bikes(id),
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  cost_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  profit NUMERIC(12,2) NOT NULL DEFAULT 0,
  payment_method TEXT NOT NULL CHECK (payment_method IN ('cash','mobile_money','bank','card','credit')),
  amount_paid NUMERIC(12,2) NOT NULL DEFAULT 0,
  change_due NUMERIC(12,2) NOT NULL DEFAULT 0,
  device_id TEXT,
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('completed','pending','pending_credit','rejected')),
  synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sales_created_at ON sales (created_at);
CREATE INDEX IF NOT EXISTS idx_sales_cashier ON sales (cashier_id);

-- Credit workflow migration: sales travel 'pending_credit' (checkout sent for
-- approval — no stock, no revenue, no debt) → 'completed' (the POS operator
-- finalized after approval) or 'rejected'. DROP + ADD runs on every boot: the
-- drop always succeeds (IF EXISTS) so the re-add is safe on old and new installs.
ALTER TABLE sales DROP CONSTRAINT IF EXISTS sales_status_check;
ALTER TABLE sales ADD CONSTRAINT sales_status_check
  CHECK (status IN ('completed','pending','pending_credit','rejected'));

CREATE TABLE IF NOT EXISTS sale_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id UUID NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id),
  bike_id UUID REFERENCES bikes(id),
  name TEXT NOT NULL,                        -- snapshot
  kind TEXT NOT NULL DEFAULT 'part' CHECK (kind IN ('part','bike')),
  qty INTEGER NOT NULL DEFAULT 1,
  unit_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  unit_cost NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount NUMERIC(12,2) NOT NULL DEFAULT 0,
  line_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product ON sale_items (product_id);

-- ============ STOCK MOVEMENTS (movement-based inventory) ============
-- type: sale | return | purchase | adjustment | workshop | damaged | transfer
CREATE TABLE IF NOT EXISTS stock_movements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  qty INTEGER NOT NULL,                      -- negative = out, positive = in
  type TEXT NOT NULL,
  sale_id UUID REFERENCES sales(id) ON DELETE SET NULL,
  user_id UUID REFERENCES users(id),
  device_id TEXT,
  client_txn_id TEXT,                        -- sale-level idempotency lives on sales.client_txn_id
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_movements_product ON stock_movements (product_id, created_at);
CREATE INDEX IF NOT EXISTS idx_movements_txn ON stock_movements (client_txn_id);

-- Migration: older installs wrongly enforced uniqueness on this column
ALTER TABLE stock_movements DROP CONSTRAINT IF EXISTS stock_movements_client_txn_id_key;

-- ============ CREDIT SALES (approval → liability → settlement) ============
-- A credit checkout saves the sale as 'pending_credit': no stock moves, no
-- revenue, no debt. Admin approval only arms the sale; the POS operator's
-- Finalize click deducts stock and opens the debt. Each payment below then
-- dissolves part of that debt and is recognized as revenue/profit on the day
-- it is received — never at sale time. Mirrors bike_installment_payments.
CREATE TABLE IF NOT EXISTS credit_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id UUID NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  payment_method TEXT NOT NULL CHECK (payment_method IN ('cash','mobile_money','bank','card')),
  paid_by UUID REFERENCES users(id),
  device_id TEXT,
  client_txn_id TEXT UNIQUE NOT NULL,        -- POS offline idempotency key
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_credit_payments_sale ON credit_payments (sale_id);
CREATE INDEX IF NOT EXISTS idx_credit_payments_created ON credit_payments (created_at);

-- ============ WEB PUSH ============
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint TEXT UNIQUE NOT NULL,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============ CONTROLS ============
-- type: discount | stock_adjustment | credit_sale | refund
CREATE TABLE IF NOT EXISTS approvals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  requested_by UUID REFERENCES users(id),
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  decided_by UUID REFERENCES users(id),
  decided_at TIMESTAMPTZ,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- POS confirms it has seen a rejection: the credit desk keeps the rejected
-- sale visible until this lands (mirrors Finalize for approved sales).
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  action TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id TEXT,
  old_value JSONB,
  new_value JSONB,
  meta JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log (created_at);

-- ============ BIKE RESERVATIONS (down payment + installments) ============
CREATE TABLE IF NOT EXISTS bike_reservations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  bike_id UUID NOT NULL REFERENCES bikes(id) ON DELETE CASCADE,
  customer_id UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  reserved_by UUID NOT NULL REFERENCES users(id),
  reserved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  total_price NUMERIC(12,2) NOT NULL CHECK (total_price >= 0),
  down_payment NUMERIC(12,2) NOT NULL CHECK (down_payment >= 0),
  balance NUMERIC(12,2) NOT NULL CHECK (balance >= 0),
  plan_months INTEGER NOT NULL DEFAULT 0 CHECK (plan_months >= 0),
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','completed','released','expired')),
  notes TEXT,
  completed_at TIMESTAMPTZ,
  released_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_reservations_bike ON bike_reservations (bike_id);
CREATE INDEX IF NOT EXISTS idx_reservations_customer ON bike_reservations (customer_id);
CREATE INDEX IF NOT EXISTS idx_reservations_status ON bike_reservations (status);

CREATE TABLE IF NOT EXISTS bike_installment_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reservation_id UUID NOT NULL REFERENCES bike_reservations(id) ON DELETE CASCADE,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  payment_method TEXT NOT NULL,
  paid_by UUID REFERENCES users(id),
  transaction_ref TEXT,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_installments_reservation ON bike_installment_payments (reservation_id);

-- ============ REVENUE RECORDS (all-time high tracking) ============
-- One row per period kind: 'week' holds the highest single ISO-week revenue
-- recorded, 'month' the highest single calendar-month revenue. The old
-- single-row (id = 1) table is migrated by the ALTERs below.
CREATE TABLE IF NOT EXISTS revenue_records (
  id INT PRIMARY KEY DEFAULT 1,
  period TEXT NOT NULL DEFAULT 'day' UNIQUE,
  revenue NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (revenue >= 0),
  date DATE NOT NULL DEFAULT CURRENT_DATE
);
ALTER TABLE revenue_records ADD COLUMN IF NOT EXISTS period TEXT NOT NULL DEFAULT 'day';
-- Older installs lack the uniqueness needed for the per-period upsert.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'revenue_records_period_key') THEN
    ALTER TABLE revenue_records ADD CONSTRAINT revenue_records_period_key UNIQUE (period);
  END IF;
END $$;

-- Migration for older installs
ALTER TABLE bikes ADD COLUMN IF NOT EXISTS reserved_at TIMESTAMPTZ;
ALTER TABLE bikes ADD COLUMN IF NOT EXISTS reserved_by UUID REFERENCES users(id);

-- ============ PURCHASING: REORDER LISTS & CONSIGNMENTS ============
-- NOTE: these tables were referenced by the purchasing routes/services but
-- were never declared in schema.sql. They are created here (idempotent) with
-- the fulfillment columns that wire "receive stock" to an existing reorder list.
CREATE TABLE IF NOT EXISTS reorder_lists (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_txn_id UUID NOT NULL UNIQUE,          -- idempotency key
  request_hash TEXT,                           -- deterministic hash of the payload
  title TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,    -- [{product_id,sku,name,qty,unit_cost,reorder_level,new_product?}]
  notes TEXT,
  created_by UUID NOT NULL REFERENCES users(id),
  fulfilled BOOLEAN NOT NULL DEFAULT FALSE,    -- TRUE once a consignment receives the items
  fulfilled_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pending',      -- pending | processed | fulfilled | cancelled
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- CREATE TABLE IF NOT EXISTS is a no-op on databases where the table already
-- exists from an earlier deploy (before fulfillment tracking was added), so the
-- columns are (re-)declared here to keep old installs upgradeable in place.
ALTER TABLE reorder_lists ADD COLUMN IF NOT EXISTS fulfilled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE reorder_lists ADD COLUMN IF NOT EXISTS fulfilled_at TIMESTAMPTZ;
ALTER TABLE reorder_lists ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
-- ADD CONSTRAINT is not idempotent across restarts, so guard it explicitly.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reorder_lists_status_check') THEN
    ALTER TABLE reorder_lists ADD CONSTRAINT reorder_lists_status_check
      CHECK (status IN ('pending', 'processed', 'fulfilled', 'cancelled'));
  END IF;
END $$;
-- Lists fulfilled before the status column existed were stamped 'pending' by the
-- ALTER default; backfill them so they stop counting as actionable everywhere.
UPDATE reorder_lists SET status = 'fulfilled'
WHERE fulfilled = TRUE AND status = 'pending';
-- Older installs also predate the updated_at maintenance column.
ALTER TABLE reorder_lists ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS idx_reorder_created ON reorder_lists (created_at);
CREATE INDEX IF NOT EXISTS idx_reorder_fulfilled ON reorder_lists (fulfilled);
CREATE INDEX IF NOT EXISTS idx_reorder_status ON reorder_lists (status);

CREATE TABLE IF NOT EXISTS consignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_txn_id UUID NOT NULL UNIQUE,          -- idempotency key
  request_hash TEXT,
  reference TEXT NOT NULL,                     -- delivery note / GRN
  supplier TEXT NOT NULL,
  delivery_cost NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (delivery_cost >= 0),
  items_total NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (items_total >= 0),
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  notes TEXT,
  source_list_id UUID REFERENCES reorder_lists(id),  -- links the received stock to the list it fulfilled
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_consignment_created ON consignments (created_at);
-- Same upgrade-in-place guard as reorder_lists above: older consignments tables
-- may predate the fulfillment link, so the column is (re-)declared idempotently.
ALTER TABLE consignments ADD COLUMN IF NOT EXISTS source_list_id UUID REFERENCES reorder_lists(id);
-- Older installs also predate the updated_at maintenance column.
ALTER TABLE consignments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS idx_consignment_source ON consignments (source_list_id);

-- Existing DBs created before the category restructure keep working: legacy
-- values are migrated to the canonical names, then the CHECK is re-widened.
--   'Spare Parts' → 'Spare Parts'        (leaf under the I.C.E group)
--   'Spare part'/'Accessory'/'Consumable' → plural canonical leaves
--   'e-Bike' → 'e-Bikes' (major section), 'e-Bike Spare Parts' → 'e-Bikes Spare Parts'
-- The constraint must be dropped BEFORE the UPDATEs: the old CHECK predates the
-- canonical values, so writing 'Spare Parts' etc. would violate it mid-migration.
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_category_check;
UPDATE products SET category = 'Spare Parts' WHERE category = 'Spare Parts';
UPDATE products SET category = 'Spare Parts' WHERE category = 'Spare part';
UPDATE products SET category = 'Accessories' WHERE category = 'Accessory';
UPDATE products SET category = 'Consumables' WHERE category = 'Consumable';
UPDATE products SET category = 'e-Bikes Spare Parts' WHERE category = 'e-Bike Spare Parts';
UPDATE products SET category = 'e-Bikes' WHERE category = 'e-Bike';
ALTER TABLE products ADD CONSTRAINT products_category_check
  CHECK (category IN ('Spare Parts','Accessories','Consumables','e-Bikes','e-Bikes Spare Parts','e-Bike','e-Bike Spare Parts','Spare Parts','Spare part','Accessory','Consumable'));


-- ============================================================
-- EXPENSES SYSTEM (new)
-- ============================================================
CREATE TABLE IF NOT EXISTS expense_categories (
    id UUID PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    group_name TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS expenses (
    id UUID PRIMARY KEY,
    client_txn_id TEXT UNIQUE,
    category_id UUID NOT NULL REFERENCES expense_categories(id),
    category_snapshot TEXT NOT NULL,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    payment_method TEXT NOT NULL CHECK (payment_method IN ('cash','mobile_money','bank','card')),
    payee TEXT,
    receipt_ref TEXT,
    expense_date DATE NOT NULL,
    notes TEXT,
    recorded_by UUID NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    voided BOOLEAN NOT NULL DEFAULT FALSE,
    void_reason TEXT,
    voided_at TIMESTAMPTZ,
    voided_by UUID REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_expenses_recorded_by ON expenses(recorded_by);

-- ============================================================
-- ADMIN SETUP + RECOVERY CODES (new)
-- ============================================================
CREATE TABLE IF NOT EXISTS admin_recovery_codes (
    id UUID PRIMARY KEY,
    code_hash TEXT NOT NULL UNIQUE,
    created_by UUID NOT NULL REFERENCES users(id),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    claimed_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_recovery_codes_expires ON admin_recovery_codes(expires_at);

-- The bootstrap setup code is generated before any user exists, so there is
-- nobody to record as its creator. (Idempotent — safe on existing installs.)
ALTER TABLE admin_recovery_codes ALTER COLUMN created_by DROP NOT NULL;

-- ============================================================
-- NOTIFICATIONS — durable cross-app inbox (admin + POS)
-- Every push payload is persisted here first (services/push.js
-- notifyAdmins/notifyUser), so a missing VAPID key, an unsubscribed
-- device or an offline terminal can never lose an event. Both apps
-- read the same table scoped to their own user.
-- ============================================================
CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL DEFAULT 'info',
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    url TEXT,
    tag TEXT,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications (user_id) WHERE read_at IS NULL;
